apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-metadata-editor.fullname" . }}-metadata-editor-svc
  labels:
    {{- include "helm-metadata-editor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
     org.geonetwork.service/name: {{ include "helm-metadata-editor.fullname" . }}-metadata-editor-deployment
