replicaCount: 1

job:
  image:
    repository: geonetwork/geonetwork-ui-tools-pipelines
    tag: 2.5.0
    pullPolicy: IfNotPresent
  schedule: "0 1 1 1 *"
  successfulJobsHistoryLimit: 3
  restartPolicy: OnFailure
  tolerations: []

config:
  elasticsearch:
    host: "http://localhost:9200"
    index: "gn-records"