replicaCount: 1

job:
  image:
    repository: geonetwork/geonetwork-ui-tools-pipelines
    tag: latest
    pullPolicy: Always
  schedule: "0 6 * * *"
  successfulJobsHistoryLimit: 3
  restartPolicy: OnFailure
  tolerations: []

config:
  elasticsearch:
    host: "http://localhost:9200"
    index: "gn-records"
