apiVersion: v2
name: datahub
description: A Helm chart to deploy the datahub application
type: application
version: 1.3.0
appVersion: "2.6.0"
maintainers:
  - name: geonetwork-ui
    url: https://geonetwork.github.io/geonetwork-ui/main/docs/
